export const RESTAURANT_STATUS = {
  PENDING: "Pending",
  APPROVED: "Approved",
  REJECTED: "Rejected",
};

export const RESTAURANT_STATUS_VALUES = [
  RESTAURANT_STATUS.PENDING,
  RESTAURANT_STATUS.APPROVED,
  RESTAURANT_STATUS.REJECTED,
];

export const RESTAURANT_VERIFICATION_STATUS = {
  PENDING: "Pending",
  VERIFIED: "Verified",
  REJECTED: "Rejected",
};

export const RESTAURANT_VERIFICATION_STATUS_VALUES = [
  RESTAURANT_VERIFICATION_STATUS.PENDING,
  RESTAURANT_VERIFICATION_STATUS.VERIFIED,
  RESTAURANT_VERIFICATION_STATUS.REJECTED,
];

export const RESTAURANT_TYPE = {
  VEG: "Veg",
  NON_VEG: "Non-Veg",
  BOTH: "Both",
};

export const RESTAURANT_TYPE_VALUES = [
  RESTAURANT_TYPE.VEG,
  RESTAURANT_TYPE.NON_VEG,
  RESTAURANT_TYPE.BOTH,
];

export const PRICE_RANGE_VALUES = ["₹", "₹₹", "₹₹₹", "₹₹₹₹"];

export const RESTAURANT_OFFER_TYPE_VALUES = [
  "Percentage",
  "Flat",
  "Free Item",
  "Other",
];

export const WEEKDAY_VALUES = [
  "Monday",
  "Tuesday",
  "Wednesday",
  "Thursday",
  "Friday",
  "Saturday",
  "Sunday",
];

export const BOOKING_PAYMENT_POLICY = {
  PAY_ON_SPOT: "PAY_ON_SPOT",
  PAY_TO_BOOK: "PAY_TO_BOOK",
};

export const BOOKING_PAYMENT_POLICY_VALUES = [
  BOOKING_PAYMENT_POLICY.PAY_ON_SPOT,
  BOOKING_PAYMENT_POLICY.PAY_TO_BOOK,
];

export const BOOKING_PAYMENT_TYPE = {
  FIXED_AMOUNT: "FIXED_AMOUNT",
  PERCENTAGE: "PERCENTAGE",
  FULL_PREORDER: "FULL_PREORDER",
};

export const BOOKING_PAYMENT_TYPE_VALUES = [
  BOOKING_PAYMENT_TYPE.FIXED_AMOUNT,
  BOOKING_PAYMENT_TYPE.PERCENTAGE,
  BOOKING_PAYMENT_TYPE.FULL_PREORDER,
];

export const MAX_BOOKING_ADVANCE_AMOUNT = 200;

export const RAZORPAY_ACCOUNT_STATUS = {
  NOT_CONNECTED: "Not Connected",
  VERIFICATION_PENDING: "Verification Pending",
  CONNECTED: "Connected & Verified",
};
