import { formatDate, formatDateTime } from "../../utils/formatDate.js";

const money = (value) => `₹${Number(value || 0).toFixed(2)}`;

export default function BillReceiptPrint({ bill, id = "receipt-pdf-area" }) {
  const booking = bill?.bookingId || {};
  const payments = bill?.payment?.payments || [];
  const status = bill?.payment?.paymentStatus || bill?.billStatus || "Pending";

  return <div id={id} className="receipt-print-root w-full overflow-hidden" style={{ background: "#ffffff", color: "#172033" }}>
    <div className="px-8 py-7" style={{ background: "#b91c1c", color: "#ffffff" }}>
      <div className="flex items-start justify-between gap-6">
        <div><p className="text-sm font-bold uppercase tracking-[0.18em]" style={{ color: "#fee2e2" }}>TableSpot</p><h1 className="mt-3 text-3xl font-black">Invoice receipt</h1><p className="mt-1 text-sm" style={{ color: "#fee2e2" }}>{bill?.billType === "WALK_IN" ? "Walk-in bill" : "Online booking bill"}</p></div>
        <div className="rounded-xl px-4 py-3 text-right" style={{ border: "1px solid rgba(255,255,255,0.3)" }}><p className="text-[10px] uppercase tracking-widest" style={{ color: "#fee2e2" }}>Bill number</p><p className="mt-1 font-mono font-bold">{bill?.billCode || "Receipt"}</p></div>
      </div>
    </div>
    <div className="p-8">
      <div className="grid grid-cols-3 gap-3"><div className="rounded-xl p-3" style={{ border: "1px solid #fee2e2", background: "#fef2f2" }}><p className="text-[10px] font-bold uppercase tracking-widest" style={{ color: "#b91c1c" }}>Restaurant</p><p className="mt-1 font-semibold">{bill?.restaurantId?.restaurantName || booking.restaurantId?.restaurantName || "Restaurant"}</p></div><div className="rounded-xl p-3" style={{ border: "1px solid #e5e7eb", background: "#f9fafb" }}><p className="text-[10px] font-bold uppercase tracking-widest" style={{ color: "#4b5563" }}>Bill date</p><p className="mt-1 font-semibold">{bill?.createdAt ? formatDate(new Date(bill.createdAt)) : "—"}</p></div><div className="rounded-xl p-3" style={{ border: "1px solid #d1fae5", background: "#ecfdf5" }}><p className="text-[10px] font-bold uppercase tracking-widest" style={{ color: "#047857" }}>Status</p><p className="mt-1 font-semibold">{status}</p></div></div>
      <div className="mt-6 grid grid-cols-2 gap-x-8 gap-y-3 border-y py-5 text-sm" style={{ borderColor: "#e5e7eb" }}><p><span className="font-semibold" style={{ color: "#4b5563" }}>Customer:</span> <span className="font-bold">{bill?.customerName || booking.userId?.fullName || "Guest"}</span></p><p><span className="font-semibold" style={{ color: "#4b5563" }}>Email:</span> <span className="font-bold">{bill?.customerEmail || booking.userId?.email || "—"}</span></p><p><span className="font-semibold" style={{ color: "#4b5563" }}>Booking number:</span> <span className="font-bold">{booking.bookingCode || "Walk-in"}</span></p><p><span className="font-semibold" style={{ color: "#4b5563" }}>Phone:</span> <span className="font-bold">{bill?.customerPhone || booking.userId?.phoneNumber || "—"}</span></p><p><span className="font-semibold" style={{ color: "#4b5563" }}>Table:</span> <span className="font-bold">{bill?.tableId?.tableCode || booking.tableId?.tableCode || bill?.tableId?.tableNumber || "—"}</span></p><p><span className="font-semibold" style={{ color: "#4b5563" }}>Booking date/time:</span> <span className="font-bold">{booking.bookingDateTime ? formatDateTime(new Date(booking.bookingDateTime)) : "—"}</span></p></div>
      <table className="mt-6 w-full border-collapse text-sm"><thead><tr className="border-b-2 text-left text-[10px] uppercase tracking-widest" style={{ borderColor: "#fecaca", color: "#991b1b" }}><th className="pb-3">Item</th><th className="pb-3">Qty</th><th className="pb-3 text-right">Unit price</th><th className="pb-3 text-right">Tax %</th><th className="pb-3 text-right">Amount</th></tr></thead><tbody>{(bill?.orderedItems || []).map((item, index) => <tr key={`${item.foodId}-${index}`} className="border-b" style={{ borderColor: "#e5e7eb" }}><td className="py-3 font-bold">{item.foodName} <span className="text-xs font-semibold" style={{ color: "#4b5563" }}>({item.variantName || "Regular"})</span></td><td className="py-3">{item.quantity}</td><td className="py-3 text-right">{money(item.unitPrice)}</td><td className="py-3 text-right">{Number(item.gstRate || bill?.taxPercentage || 0)}%</td><td className="py-3 text-right font-bold">{money(item.totalPrice)}</td></tr>)}</tbody></table>
      <div className="mt-6 ml-auto w-80 rounded-xl p-4 text-sm" style={{ background: "#f9fafb" }}><div className="flex justify-between py-1"><span className="font-semibold" style={{ color: "#4b5563" }}>Subtotal</span><span className="font-semibold">{money(bill?.subTotal)}</span></div><div className="flex justify-between py-1"><span className="font-semibold" style={{ color: "#4b5563" }}>Discount</span><span className="font-bold" style={{ color: "#047857" }}>-{money(bill?.discount?.value)}</span></div><div className="flex justify-between py-1"><span className="font-semibold" style={{ color: "#4b5563" }}>Taxable Amount</span><span className="font-semibold">{money(bill?.taxableAmount)}</span></div><div className="flex justify-between py-1"><span className="font-semibold" style={{ color: "#4b5563" }}>Tax ({bill?.taxPercentage || 0}%)</span><span className="font-semibold">{money(bill?.taxAmount)}</span></div><div className="mt-2 flex justify-between border-t pt-3 text-lg font-black" style={{ borderColor: "#d1d5db" }}><span>Grand Total</span><span style={{ color: "#b91c1c" }}>{money(bill?.grandTotal)}</span></div><div className="mt-3 flex justify-between border-t border-dashed pt-3" style={{ borderColor: "#d1d5db" }}><span className="font-semibold" style={{ color: "#4b5563" }}>Total Paid</span><span className="font-bold" style={{ color: "#047857" }}>{money(bill?.payment?.totalPaid)}</span></div><div className="flex justify-between font-bold"><span style={{ color: "#4b5563" }}>Balance Due</span><span style={{ color: "#b91c1c" }}>{money(bill?.payment?.balanceDue)}</span></div></div>
      <div className="mt-6 rounded-xl p-4" style={{ border: "1px solid #e5e7eb" }}><p className="mb-3 text-[10px] font-bold uppercase tracking-widest" style={{ color: "#4b5563" }}>Payment history</p>{payments.length ? payments.map((payment, index) => <div key={`${payment.transactionId || index}`} className="flex justify-between border-b py-2 last:border-0" style={{ borderColor: "#e5e7eb" }}><span className="font-bold">{payment.paymentMethod || "Cash"}{payment.transactionId ? ` · ${payment.transactionId}` : ""}</span><span className="font-bold">{money(payment.amount)}</span></div>) : <p className="text-sm" style={{ color: "#6b7280" }}>No payments recorded</p>}</div>
    </div>
  </div>;
}
