import { Plus, Trash2, UtensilsCrossed } from "lucide-react";
import Button from "../ui/Button.jsx";
import Input from "../ui/Input.jsx";
import Select from "../ui/Select.jsx";

export default function BillItems({ items, taxPercentage, foods, loading, selectedFoodId, selectedVariant, quantity, onFoodChange, onVariantChange, onQuantityChange, onAdd, onChange }) {
  const selectedFood = foods.find((food) => food._id === selectedFoodId);
  return <section className="rounded-2xl border border-border bg-surface-secondary/40 p-4 sm:p-5"><h3 className="mb-3 flex items-center gap-2 text-sm font-semibold text-text"><UtensilsCrossed size={16} className="text-primary" />Items</h3>
    <div className="overflow-x-auto rounded-xl border border-border"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-surface-secondary text-xs uppercase text-muted"><tr>{["S.No", "Food", "Variant", "Quantity", "Unit Price", "Tax %", "Item Total", "Action"].map((heading) => <th key={heading} className="px-3 py-2">{heading}</th>)}</tr></thead><tbody className="divide-y divide-border">{items.map((item, index) => <tr key={`${item.foodId}-${item.variantName}-${index}`}><td className="px-3 py-3">{index + 1}</td><td className="px-3 py-3 font-medium">{item.foodName}</td><td className="px-3 py-3">{item.variantName}</td><td className="px-3 py-3"><div className="flex items-center gap-1"><Button type="button" size="sm" variant="outline" disabled={item.quantity <= 1} onClick={() => onChange(items.map((row, i) => i === index ? { ...row, quantity: row.quantity - 1 } : row))}>−</Button><span>{item.quantity}</span><Button type="button" size="sm" variant="outline" onClick={() => onChange(items.map((row, i) => i === index ? { ...row, quantity: row.quantity + 1 } : row))}>+</Button></div></td><td className="px-3 py-3">₹{Number(item.unitPrice || 0).toFixed(2)}</td><td className="px-3 py-3">{Number(taxPercentage) || 0}%</td><td className="px-3 py-3 font-semibold">₹{Number(item.totalPrice || (item.unitPrice || 0) * item.quantity).toFixed(2)}</td><td className="px-3 py-3"><Button type="button" size="sm" variant="ghost" className="text-red-600" onClick={() => onChange(items.filter((_, i) => i !== index))}><Trash2 size={14} /></Button></td></tr>)}</tbody></table></div>
    <div className="mt-4 grid gap-3 sm:grid-cols-[1fr_1fr_auto_auto] sm:items-end"><Select label="Food" value={selectedFoodId} onChange={(event) => onFoodChange(event.target.value)}><option value="">-- Choose item --</option>{foods.map((food) => <option key={food._id} value={food._id}>{food.foodName}</option>)}</Select><Select label="Variant" value={selectedVariant} onChange={(event) => onVariantChange(event.target.value)} disabled={!selectedFood || !selectedFood.hasVariants}>{(selectedFood?.variants || []).map((variant) => <option key={variant.variantName} value={variant.variantName}>{variant.variantName}</option>)}{!selectedFood?.hasVariants && <option value="Regular">Regular</option>}</Select><Input label="Quantity" type="number" min="1" value={quantity} onChange={(event) => onQuantityChange(event.target.value)} /><Button type="button" variant="secondary" onClick={onAdd} disabled={loading || !selectedFood}><Plus size={15} className="mr-1" />Add Spot Food</Button></div>
  </section>;
}
