import Bill from "../models/Bill.js";
import Booking from "../models/Booking.js";
import User from "../models/User.js";

import ApiError from "../utils/ApiError.js";
import generateCode from "../utils/generateCode.js";

import {
  BILL_STATUS,
  CODE_PREFIX,
  DISCOUNT_TYPE,
  PAYMENT_METHOD,
  PAYMENT_STATUS,
} from "../utils/constants.js";

const roundAmount = (value) => Math.round(Number(value || 0) * 100) / 100;

const normalizeOrderedItems = (items = []) =>
  items.map((item) => ({
    foodId: item.foodId,
    foodName: String(item.foodName).trim(),
    variantName: item.variantName?.trim() || "Regular",
    quantity: Number(item.quantity),
    unitPrice: Number(item.unitPrice),
    offerPrice: Number(item.offerPrice || 0),
    totalPrice:
      item.totalPrice !== undefined && item.totalPrice !== null
        ? Number(item.totalPrice)
        : roundAmount(
            Number(item.quantity || 0) *
              Math.max(0, Number(item.unitPrice || 0) - Number(item.offerPrice || 0))
          ),
    orderSource: item.orderSource || "Spot Order",
  }));

const calculateSubTotal = (orderedItems = []) =>
  roundAmount(
    orderedItems.reduce(
      (sum, item) => sum + Number(item.totalPrice || 0),
      0
    )
  );

const calculateDiscountAmount = (discount = {}, subTotal = 0) => {
  if (!discount || !discount.type || !discount.value) {
    return 0;
  }

  const value = Number(discount.value || 0);

  if (discount.type === DISCOUNT_TYPE.PERCENTAGE) {
    return roundAmount(Math.min(subTotal, (subTotal * value) / 100));
  }

  return roundAmount(Math.min(subTotal, value));
};

const calculatePaymentSummary = ({
  payment = {},
  grandTotal = 0,
}) => {
  const payments = Array.isArray(payment.payments)
    ? payment.payments
    : [];

  const paymentsTotal = roundAmount(
    payments.reduce((sum, item) => sum + Number(item.amount || 0), 0)
  );

  const totalPaid = roundAmount(
    payment.totalPaid ??
      payment.advancePaid ??
      payment.spotPaid ??
      paymentsTotal
  );

  const advancePaid = roundAmount(payment.advancePaid || 0);
  const spotPaid = roundAmount(payment.spotPaid || 0);
  const balanceDue = roundAmount(Math.max(0, grandTotal - totalPaid));

  let paymentStatus = PAYMENT_STATUS.PENDING;

  if (totalPaid <= 0) {
    paymentStatus = PAYMENT_STATUS.PENDING;
  } else if (balanceDue <= 0) {
    paymentStatus = PAYMENT_STATUS.PAID;
  } else {
    paymentStatus = PAYMENT_STATUS.PARTIALLY_PAID;
  }

  return {
    totalPaid,
    advancePaid,
    spotPaid,
    balanceDue,
    paymentStatus,
    payments,
  };
};

const getBillOrThrow = async (billId) => {
  const bill = await Bill.findById(billId);

  if (!bill || bill.isDeleted) {
    throw new ApiError(404, "Bill not found.");
  }

  return bill;
};

const getBookingOrThrow = async (bookingId) => {
  const booking = await Booking.findById(bookingId);

  if (!booking || booking.isDeleted) {
    throw new ApiError(404, "Booking not found.");
  }

  return booking;
};

const populateBill = (query) =>
  query
    .populate("bookingId")
    .populate("generatedBy", "userCode fullName email phoneNumber role profileImage");

const buildBillTotals = ({
  orderedItems,
  discount,
  taxAmount = 0,
  serviceCharge = 0,
  deliveryCharge = 0,
  payment = {},
}) => {
  const normalizedItems = normalizeOrderedItems(orderedItems);
  const subTotal = calculateSubTotal(normalizedItems);
  const discountAmount = calculateDiscountAmount(discount, subTotal);
  const tax = roundAmount(taxAmount);
  const service = roundAmount(serviceCharge);
  const delivery = roundAmount(deliveryCharge);
  const grandTotal = roundAmount(
    Math.max(0, subTotal - discountAmount + tax + service + delivery)
  );
  const paymentSummary = calculatePaymentSummary({
    payment,
    grandTotal,
  });

  return {
    orderedItems: normalizedItems,
    subTotal,
    discount: discount || { type: DISCOUNT_TYPE.AMOUNT, value: 0 },
    taxAmount: tax,
    serviceCharge: service,
    deliveryCharge: delivery,
    grandTotal,
    payment: paymentSummary,
  };
};

export const createBill = async ({
  bookingId,
  orderedItems = [],
  discount = null,
  taxAmount = 0,
  serviceCharge = 0,
  deliveryCharge = 0,
  notes = "",
  generatedBy,
  generatedAt = new Date(),
  payment = {},
}) => {
  if (!bookingId) {
    throw new ApiError(400, "Booking is required.");
  }

  if (!generatedBy) {
    throw new ApiError(400, "Generated by user is required.");
  }

  const user = await User.findById(generatedBy).select("_id isActive isDeleted");
  if (!user || !user.isActive || user.isDeleted) {
    throw new ApiError(404, "Generator user not found.");
  }

  const booking = await getBookingOrThrow(bookingId);

  if (booking.billId) {
    throw new ApiError(409, "A bill already exists for this booking.");
  }

  if (!Array.isArray(orderedItems) || orderedItems.length === 0) {
    throw new ApiError(400, "Ordered items are required to create a bill.");
  }

  const billCode = await generateCode(
    Bill,
    "billCode",
    CODE_PREFIX.BILL
  );

  const totals = buildBillTotals({
    orderedItems,
    discount,
    taxAmount,
    serviceCharge,
    deliveryCharge,
    payment,
  });

  const bill = await Bill.create({
    billCode,
    bookingId: booking._id,
    orderedItems: totals.orderedItems,
    subTotal: totals.subTotal,
    discount: totals.discount,
    taxAmount: totals.taxAmount,
    serviceCharge: totals.serviceCharge,
    deliveryCharge: totals.deliveryCharge,
    grandTotal: totals.grandTotal,
    payment: totals.payment,
    billStatus: BILL_STATUS.GENERATED,
    notes: notes.trim(),
    generatedBy,
    generatedAt,
  });

  booking.billId = bill._id;
  booking.totalAmount = totals.grandTotal;
  booking.paymentStatus = totals.payment.paymentStatus;
  booking.paymentMethod = booking.paymentMethod || "Cash";
  await booking.save();

  return {
    bill: await populateBill(Bill.findById(bill._id)),
    message: "Bill created successfully.",
  };
};

export const updateBill = async ({
  billId,
  updates = {},
}) => {
  const bill = await getBillOrThrow(billId);

  if (updates.orderedItems !== undefined) {
    bill.orderedItems = normalizeOrderedItems(updates.orderedItems);
  }

  if (updates.discount !== undefined) {
    bill.discount = updates.discount;
  }

  const numericFields = [
    "taxAmount",
    "serviceCharge",
    "deliveryCharge",
  ];

  for (const field of numericFields) {
    if (updates[field] !== undefined) {
      bill[field] = Number(updates[field]);
    }
  }

  if (updates.notes !== undefined) {
    bill.notes = String(updates.notes).trim();
  }

  if (updates.billStatus !== undefined) {
    bill.billStatus = updates.billStatus;
  }

  if (updates.generatedAt !== undefined) {
    bill.generatedAt = updates.generatedAt ? new Date(updates.generatedAt) : updates.generatedAt;
  }

  if (updates.isActive !== undefined) {
    bill.isActive = Boolean(updates.isActive);
  }

  const paymentUpdates = updates.payment || {};
  const existingPayment = bill.payment?.payments || [];

  const totals = buildBillTotals({
    orderedItems: bill.orderedItems,
    discount: bill.discount,
    taxAmount: bill.taxAmount,
    serviceCharge: bill.serviceCharge,
    deliveryCharge: bill.deliveryCharge,
    payment: {
      ...bill.payment?.toObject?.() ?? bill.payment ?? {},
      ...paymentUpdates,
      payments: paymentUpdates.payments || existingPayment,
    },
  });

  bill.orderedItems = totals.orderedItems;
  bill.subTotal = totals.subTotal;
  bill.discount = totals.discount;
  bill.taxAmount = totals.taxAmount;
  bill.serviceCharge = totals.serviceCharge;
  bill.deliveryCharge = totals.deliveryCharge;
  bill.grandTotal = totals.grandTotal;
  bill.payment = totals.payment;

  if (bill.payment.paymentStatus === PAYMENT_STATUS.PAID) {
    bill.billStatus = BILL_STATUS.PAID;
  }

  await bill.save();

  const booking = await Booking.findById(bill.bookingId);
  if (booking) {
    booking.totalAmount = bill.grandTotal;
    booking.paymentStatus = bill.payment.paymentStatus;
    await booking.save();
  }

  return {
    bill: await populateBill(Bill.findById(bill._id)),
    message: "Bill updated successfully.",
  };
};

export const addBillPayment = async ({
  billId,
  paymentMethod,
  amount,
  transactionId = "",
  notes = "",
  paidAt = new Date(),
}) => {
  const bill = await getBillOrThrow(billId);

  if (!Object.values(PAYMENT_METHOD).includes(paymentMethod)) {
    throw new ApiError(400, "Invalid payment method.");
  }

  const paymentEntry = {
    paymentMethod,
    amount: Number(amount),
    transactionId: transactionId.trim(),
    notes: notes.trim(),
    paidAt,
  };

  bill.payment = bill.payment || {};
  bill.payment.payments = bill.payment.payments || [];
  bill.payment.payments.push(paymentEntry);

  const totals = buildBillTotals({
    orderedItems: bill.orderedItems,
    discount: bill.discount,
    taxAmount: bill.taxAmount,
    serviceCharge: bill.serviceCharge,
    deliveryCharge: bill.deliveryCharge,
    payment: bill.payment,
  });

  bill.payment = totals.payment;
  bill.billStatus =
    bill.payment.paymentStatus === PAYMENT_STATUS.PAID
      ? BILL_STATUS.PAID
      : bill.billStatus;

  await bill.save();

  const booking = await Booking.findById(bill.bookingId);
  if (booking) {
    booking.paymentStatus = bill.payment.paymentStatus;
    await booking.save();
  }

  return {
    bill: await populateBill(Bill.findById(bill._id)),
    message: "Payment added successfully.",
  };
};

export const markBillStatus = async ({
  billId,
  billStatus,
}) => {
  const bill = await getBillOrThrow(billId);

  bill.billStatus = billStatus;

  if (billStatus === BILL_STATUS.PAID) {
    bill.payment = bill.payment || {};
    bill.payment.paymentStatus = PAYMENT_STATUS.PAID;
    bill.payment.balanceDue = 0;
  }

  await bill.save();

  const booking = await Booking.findById(bill.bookingId);
  if (booking) {
    booking.paymentStatus = bill.payment?.paymentStatus || booking.paymentStatus;
    await booking.save();
  }

  return {
    bill: await populateBill(Bill.findById(bill._id)),
    message: "Bill status updated successfully.",
  };
};

export const getBillById = async ({
  billId,
}) => {
  const bill = await populateBill(Bill.findById(billId));

  if (!bill || bill.isDeleted) {
    throw new ApiError(404, "Bill not found.");
  }

  return {
    bill,
  };
};

export const getBills = async ({
  page = 1,
  limit = 10,
  bookingId = null,
  billStatus = null,
  paymentStatus = null,
  generatedBy = null,
}) => {
  const query = { isDeleted: false };

  if (bookingId) {
    query.bookingId = bookingId;
  }

  if (billStatus) {
    query.billStatus = billStatus;
  }

  if (paymentStatus) {
    query["payment.paymentStatus"] = paymentStatus;
  }

  if (generatedBy) {
    query.generatedBy = generatedBy;
  }

  const pageNumber = Math.max(Number(page) || 1, 1);
  const pageSize = Math.min(Math.max(Number(limit) || 10, 1), 100);
  const skip = (pageNumber - 1) * pageSize;

  const [bills, total] = await Promise.all([
    Bill.find(query)
      .sort({ createdAt: -1 })
      .skip(skip)
      .limit(pageSize)
      .populate("bookingId")
      .populate("generatedBy", "userCode fullName email phoneNumber role profileImage"),
    Bill.countDocuments(query),
  ]);

  return {
    bills,
    meta: {
      page: pageNumber,
      limit: pageSize,
      total,
      totalPages: Math.ceil(total / pageSize) || 1,
    },
  };
};
